#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2025 TeamUltroid
#
# This file is a part of < https://github.com/TeamUltroid/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git redis -y
    git clone https://github.com/TeamUltroid/Ultroid
    cd Ultroid
fi
bash resources/startup/termux.sh
