# Ultroid - UserBot
# Copyright (C) 2021-2026 TeamUltroid
#
# This file is a part of < https://github.com/TeamUltroid/Ultroid/ >
# PLease read the GNU Affero General Public License in
# <https://github.com/TeamUltroid/pyUltroid/blob/main/LICENSE>.

"""Guided local setup. Hosted platforms should set config vars in the dashboard instead.

Usage:
  python -m pyUltroid setup
  python -m pyUltroid doctor
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path.cwd()
ENV_PATH = ROOT / ".env"
ENV_SAMPLE = ROOT / ".env.sample"

PROFILES = {
    "minimal": ["requirements.txt"],
    "db-redis": ["requirements.txt", "requirements-db-redis.txt"],
    "db-mongo": ["requirements.txt", "requirements-db-mongo.txt"],
    "db-postgres": ["requirements.txt", "requirements-db-postgres.txt"],
    "full": ["requirements.txt", "requirements-full.txt"],
    "termux": ["requirements.txt"],
}


def _is_interactive() -> bool:
    return sys.stdin.isatty() and sys.stdout.isatty()


def _prompt(msg: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default not in (None, "") else ""
    try:
        val = input(f"{msg}{suffix}: ").strip()
    except EOFError:
        return default or ""
    return val if val else (default or "")


def _yes(msg: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    ans = _prompt(f"{msg} ({hint})", "y" if default else "n").lower()
    if not ans:
        return default
    return ans in {"y", "yes", "1", "true"}


def _write_env(values: dict[str, str]) -> None:
    lines = [
        "# Generated by: python -m pyUltroid setup",
        "# Don't use quotes ( \" and ' )",
        "",
    ]
    order = [
        "API_ID",
        "API_HASH",
        "SESSION",
        "BOT_TOKEN",
        "LOG_CHANNEL",
        "REDIS_URI",
        "REDIS_PASSWORD",
        "MONGO_URI",
        "DATABASE_URL",
        "ADDONS",
        "VCBOT",
        "ULTROID_AUTO_PIP",
        "ULTROID_STRICT_CONFIG",
        "SKIP_AUTOPILOT",
        "SKIP_AUTOJOIN",
        "SKIP_AUTOBOT",
        "SKIP_ASSISTANT_CUSTOMIZE",
    ]
    seen = set()
    for key in order:
        if key in values and values[key] not in (None, ""):
            lines.append(f"{key}={values[key]}")
            seen.add(key)
    for key, val in values.items():
        if key not in seen and val not in (None, ""):
            lines.append(f"{key}={val}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {ENV_PATH}")


def _pip_install(req_files: list[str]) -> int:
    for req in req_files:
        path = ROOT / req
        if not path.exists():
            print(f"  skip missing {req}")
            continue
        print(f"  pip install -r {req}")
        rc = subprocess.call(
            [sys.executable, "-m", "pip", "install", "-q", "--no-cache-dir", "-r", str(path)]
        )
        if rc != 0:
            return rc
    return 0


def _probe_import(name: str) -> bool:
    try:
        __import__(name)
        return True
    except Exception:
        return False


def cmd_doctor() -> int:
    print("Ultroid doctor\n" + "-" * 40)
    print(f"Python     : {platform.python_version()} ({sys.executable})")
    print(f"Platform   : {platform.platform()}")
    print(f"Cwd        : {ROOT}")
    print(f".env       : {'yes' if ENV_PATH.exists() else 'no'}")
    print(f"plugins/   : {'yes' if (ROOT / 'plugins').is_dir() else 'MISSING'}")
    print(f"ffmpeg     : {shutil.which('ffmpeg') or 'not found'}")
    print(f"mediainfo  : {shutil.which('mediainfo') or 'not found'}")
    print(f"git        : {shutil.which('git') or 'not found'}")

    mods = {
        "telethon": "telethon",
        "decouple": "decouple",
        "dotenv": "dotenv",
        "redis": "redis",
        "pymongo": "pymongo",
        "psycopg2": "psycopg2",
        "localdb": "localdb",
        "pytz": "pytz",
        "apscheduler": "apscheduler",
        "heroku3": "heroku3",
        "yt_dlp": "yt_dlp",
    }
    print("\nPython packages:")
    for label, mod in mods.items():
        ok = _probe_import(mod)
        print(f"  {'OK' if ok else '--'}  {label}")

    # Light config check without full boot
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    try:
        import importlib.util

        # Load config_validate without importing pyUltroid package side effects
        cv_path = ROOT / "pyUltroid" / "startup" / "config_validate.py"
        spec = importlib.util.spec_from_file_location("ultroid_config_validate", cv_path)
        cv = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(cv)

        try:
            from decouple import config as _cfg
        except ImportError:
            print("\nConfig:")
            print("  WARN: python-decouple not installed — install requirements.txt")
            print("  (package probe above already lists missing deps)")
            return 0

        class _Var:
            API_ID = _cfg("API_ID", default=None)
            API_HASH = _cfg("API_HASH", default=None)
            SESSION = _cfg("SESSION", default=None)
            REDIS_URI = _cfg("REDIS_URI", default=None) or _cfg("REDIS_URL", default=None)
            REDISHOST = _cfg("REDISHOST", default=None)
            REDISPORT = _cfg("REDISPORT", default=None)
            MONGO_URI = _cfg("MONGO_URI", default=None)
            DATABASE_URL = _cfg("DATABASE_URL", default=None)
            BOT_TOKEN = _cfg("BOT_TOKEN", default=None)

        try:
            if _Var.API_ID is not None:
                _Var.API_ID = int(_Var.API_ID)
        except (TypeError, ValueError):
            pass

        errors, warnings = cv.collect_config_issues(_Var)
        print("\nConfig:")
        if not errors and not warnings:
            print("  OK — no issues detected")
        for w in warnings:
            print(f"  WARN: {w.splitlines()[0]}")
        for e in errors:
            print(f"  ERR:  {e.splitlines()[0]}")
        return 1 if errors else 0
    except Exception as er:
        print(f"\nConfig check skipped: {er}")
        return 0


def cmd_setup() -> int:
    print(
        """
╔══════════════════════════════════════╗
║         Ultroid setup wizard         ║
╚══════════════════════════════════════╝
Hosted (Heroku/Railway/etc.): set config vars in the dashboard — do not run this there.
Local/VPS: follow the prompts. Non-interactive: use .env.sample → .env
"""
    )
    if not _is_interactive():
        print(
            "Non-interactive terminal detected.\n"
            f"Copy {ENV_SAMPLE.name} to .env, fill values, then:\n"
            "  pip install -r requirements.txt\n"
            "  pip install -r requirements-db-redis.txt   # or mongo/postgres\n"
            "  bash sessiongen\n"
            "  python -m pyUltroid\n"
        )
        if ENV_SAMPLE.exists() and not ENV_PATH.exists():
            shutil.copy(ENV_SAMPLE, ENV_PATH)
            print(f"Created {ENV_PATH} from sample — edit it before starting.")
        return 0

    if not (ROOT / "plugins").is_dir() or not (ROOT / "pyUltroid").is_dir():
        print("Run this from the Ultroid repo root (plugins/ and pyUltroid/ required).")
        return 1

    values: dict[str, str] = {}
    print("Get API credentials from https://my.telegram.org\n")
    values["API_ID"] = _prompt("API_ID")
    values["API_HASH"] = _prompt("API_HASH")
    values["SESSION"] = _prompt(
        "SESSION string (leave empty and run bash sessiongen later)", ""
    )
    values["BOT_TOKEN"] = _prompt(
        "BOT_TOKEN (optional — autopilot can create one)", ""
    )
    values["LOG_CHANNEL"] = _prompt("LOG_CHANNEL id (optional)", "")

    print("\nDatabase backend:")
    print("  1) Redis (recommended)")
    print("  2) MongoDB")
    print("  3) PostgreSQL")
    print("  4) Local file DB (dev only)")
    choice = _prompt("Choice", "1")
    profile = "minimal"
    if choice == "1":
        values["REDIS_URI"] = _prompt("REDIS_URI (host:port, no redis://)")
        values["REDIS_PASSWORD"] = _prompt("REDIS_PASSWORD", "")
        profile = "db-redis"
    elif choice == "2":
        values["MONGO_URI"] = _prompt("MONGO_URI")
        profile = "db-mongo"
    elif choice == "3":
        values["DATABASE_URL"] = _prompt("DATABASE_URL (postgres://...)")
        profile = "db-postgres"
    else:
        profile = "minimal"
        print("Using LocalDB — fine for trials, not production.")

    if _yes("Install full optional plugin dependencies?", default=False):
        profile = "full"

    values["ADDONS"] = "True" if _yes("Enable UltroidAddons?", default=False) else "False"
    values["VCBOT"] = "True" if _yes("Enable VCBOT?", default=False) else "False"

    print("\nAutopilot side-effects (safe defaults for first run):")
    values["SKIP_AUTOJOIN"] = (
        "True" if _yes("Skip auto-join @TheUltroid?", default=False) else "False"
    )
    values["SKIP_AUTOBOT"] = (
        "True"
        if _yes("Skip auto BotFather bot creation (set BOT_TOKEN yourself)?", default=False)
        else "False"
    )
    values["SKIP_ASSISTANT_CUSTOMIZE"] = (
        "True" if _yes("Skip assistant @BotFather customization?", default=True) else "False"
    )
    values["ULTROID_AUTO_PIP"] = (
        "1" if _yes("Allow runtime pip install fallback?", default=True) else "0"
    )
    values["ULTROID_STRICT_CONFIG"] = (
        "1" if _yes("Strict config (require remote DB)?", default=False) else "0"
    )

    if ENV_PATH.exists() and not _yes(f"Overwrite existing {ENV_PATH}?", default=False):
        print("Keeping existing .env")
    else:
        _write_env(values)

    if _yes(f"Install Python deps (profile: {profile})?", default=True):
        reqs = PROFILES.get(profile, PROFILES["minimal"])
        rc = _pip_install(reqs)
        if rc != 0:
            print("pip failed — install requirements manually.")
            return rc

    if not values.get("SESSION"):
        print(
            "\nNo SESSION yet. Generate one:\n"
            "  bash sessiongen\n"
            "Then put the string in .env as SESSION=..."
        )

    print(
        "\nDone. Start Ultroid with:\n"
        "  bash startup\n"
        "  # or: python -m pyUltroid\n"
        "\nHealth check anytime:\n"
        "  python -m pyUltroid doctor\n"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = list(argv if argv is not None else sys.argv[1:])
    if not argv or argv[0] in {"-h", "--help", "help"}:
        print(__doc__)
        return 0
    cmd = argv[0]
    if cmd == "setup":
        return cmd_setup()
    if cmd == "doctor":
        return cmd_doctor()
    print(f"Unknown command: {cmd}\n{__doc__}")
    return 2
