FROM mcr.microsoft.com/vscode/devcontainers/base:0.202.2-debian-11

RUN sudo apt update && \
	sudo apt -y upgrade && \
	sudo apt -y install python3-venv python3-pip && \
	python3 -m pip install --upgrade pip

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
