FROM mcr.microsoft.com/vscode/devcontainers/base:0.202.2-alpine3.14

RUN apk update && \
	apk add build-base && \
	apk add python3-dev && \
	apk add linux-headers && \
	apk add --update --no-cache python3 py3-pip

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)