name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: ultroid
          stack: "container"
          region: "us"
        env:
          HD_API_ID: ${{secrets.API_ID}}
          HD_API_HASH: ${{secrets.API_HASH}}
          HD_SESSION: ${{secrets.SESSION}}
          HD_REDIS_URI: ${{secrets.REDIS_URI}}
          HD_REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
          HD_HEROKU_API: ${{secrets.HEROKU_API_KEY}}
          HD_HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
